install.packages("ggplot2", dependencies=TRUE)
install.packages("plyr")
install.packages("ggthemes")
install.packages("reshape2")

library("ggplot2")
library("plyr")
library("ggthemes")
library("reshape2")

head(iris)
myplot <- ggplot(data = iris, aes(x = Sepal.Length. y = Sepal.Width))
summary(myplot)
myplot <- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width))
summary(myplot)
myplot <- ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()
myplot
ggplot(data = iris, aes(x = Sepal.Length, y = Sepal.Width)) +
  geom_point()
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(size = 3)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(aes(shape = Species), size = 3)
d2 <- diamonds[sample(1:dim(diamonds)[1], 1000), ]
head(d2)
myplot <- ggplot(data = d2, aes(x = carat, y = price))
myplot <- ggplot(data = d2, aes(x = carat, y = price)) + geom_point()       
ggplot(data = d2, aes(x = carat, y = price)) + geom_point()       
library(MASS)
library(MASS)
ggplot(birthwt, aes(factor(race), bwt)) + geom_boxplot()
ggplot(birthwt, aes(factor(race), bwt)) + geom_boxplot()
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point() + facet_grid(Species ~ .)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point() + facet_wrap( ~ Species)
library(RColorBrewer)
df <- melt(iris, id.vars = "Species")
ggplot(df, aes(Species, value, fill= variable)) + geom_bar(stat = "identity", position = "dodge") + scale_fill_brewer(palette = "Set1")
h <- ggplot(faithful, aes(x = waiting))
h + geom_histogram(binwidth = 8, fill = "steelblue", color = "black")
ggplot(iris, aes(Species, Sepal.Length)) + geom_bar(stat = "identity")
ggplot(d2, aes(carat, clarity)) + geom_point()
ggplot(d2, aes(carat, clarity)) + geom_point() + facet_grid( ~ cut)
ggplot(d2, aes(clarity, fill = cut)) + geom_bar(position = "dodge")
ggplot(faithful, aes(waiting)) + geom_density(fill = "blue", aplha = 0.1)
ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + geom_point(aes(shape = Species), size = 3) + geom_smooth(method = "lm")
